Sync with Master for large update
ROBOTIS-GIT/emanual pull request #1724
Opened 2024-12-17 18:40 UTC by Jonathon-RINC

2024-12-17 18:44 UTC, Jonathon-RINC commented
@robotpilot 
I believe that all conflicts should be resolved and this compilation of changes should be eligible for merge.

Please let me know if anything else is required.

2024-12-17 22:13 UTC, robotpilot requested changes
I've found issues in a few places and left comments on each code. 
Please take note and reconsider.

2024-12-17 22:13 UTC, robotpilot commented on _includes/en/dxl/x/baudrate.md
> +<<<<<<< HEAD
There seems to be a conflict here, please review it again.

2024-12-17 22:13 UTC, robotpilot commented on _includes/en/dxl/x/indirect_data.md
> +<<<<<<< HEAD
Please double-check this - if you see the "<<<<<" or ">>>>>" mark, you should look carefully.

2024-12-17 22:13 UTC, robotpilot commented on _includes/en/dxl/y/output_bearing_y_m.md
> +<<<<<<< HEAD
Please double-check this and this page.

2024-12-17 22:54 UTC, Jonathon-RINC commented
Thank you for the review, I believe that all the reported issues have been resolved in the latest commits just added.

2024-12-17 23:31 UTC, robotpilot approved these changes
LGTM, Thanks @Jonathon-RINC :)

2024-12-17 23:35 UTC, robotpilot commented
HI, @ROBOTIS-Yang 
@Jonathon-RINC had a request to improve the manual. 
Overall, it's very good. I'd like to ask you to give it a final review and merge it if there are no issues, 
but if you find any issue, please let me know. 
Have a nice day. :)

2024-12-18 01:00 UTC, ROBOTIS-Yang commented on _includes/en/dxl/assembly/xl430_frame_assembly.md
Please add the links

2024-12-18 01:44 UTC, robotpilot commented
@Jonathon-RINC, 
We've found some things to fix, so we'll change the branch to merge and do the merge first, 
and then we'll push a fix commit to that branch so we can do the final merge. Thank you.

2024-12-18 01:45 UTC, merged

2024-12-18 01:48 UTC, Jonathon-RINC commented
@robotpilot 
Understood, thank you for working with me to get these changes merged.